version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: games
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - '5432:5432'

volumes:
  postgres-db:
    driver: local
